name: CI monthly

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
        default: '6-php7.4'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Build
        run: |
          docker build -t ghcr.io/utaustin-laits/wordpress-base:${{ github.event.inputs.version }} ${{ github.event.inputs.version }}
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker push ghcr.io/utaustin-laits/wordpress-base:${{ github.event.inputs.version }}
